name: SymbCompCC
version: 1.2
date: 2011-11-19
description: |
    Computing with parametrised presentations for p-groups of fixed coclass

authors:
    - name: Dörte Feichtenschlager
      url: mailto:d.feichtenschlager@tu-braunschweig.de

maintainers:
    - name: Dörte Feichtenschlager
      url: mailto:d.feichtenschlager@tu-braunschweig.de

GAP: ">=4.5"

needed-pkgs:
    - name: "polycyclic"
      version: ">= 2.2"
      url: "https://gap-packages.github.io/polycyclic/"

www: http://www.icm.tu-bs.de/ag_algebra/software/SymbCompCC
readme: README
packageinfo: http://www.icm.tu-bs.de/ag_algebra/software/feichten/SymbCompCC/PackageInfo.g

downloads:
    - name: .tar.bz2,
      url: http://www.icm.tu-bs.de/ag_algebra/software/feichten/SymbCompCC/SymbCompCC-1.2.tar.bz2,
    - name: .tar.gz
      url: http://www.icm.tu-bs.de/ag_algebra/software/feichten/SymbCompCC/SymbCompCC-1.2.tar.gz

abstract: |
    The <span class="pkgname">SymbCompCC</span> package computes with parametrised presentations for finite p-groups of fixed coclass.

status: accepted
doc-html: htm/chapters.htm
doc-pdf: doc/manual.pdf
